OriginProtocol/ousd-analytics

eagleproject/core/sigs.py
eagleproject/notify/triggers/ousd_mint.py
eagleproject/notify/triggers/ousd_totalsupply.py

As the title says.  Showing notifications for TotalSupplyUpdated during mint/redeems are confusing.  This skips them if the transaction is paired with one of those events.  It also raises the severity to make it more prominent if it does occur without either of those events.
CC @tomlinton @franckc 
Ref: #24

Skip TotalSupplyUpdated when they occur with a mint or redeem

---

eagleproject/core/templates/apr_index.html
eagleproject/core/templates/dashboard.html
eagleproject/core/views.py

Calculates the APR by using the OUSD rebase ratio.
This has the upside that it's simple to calculate and exactly matches user's balance changes.
It has the downside that the number it pulls from only gets updated on rebases, making this method less acurate. It's bit iffy using it on only one day, but that's the data we have at the moment.

Switch to one day trailing APR

---

eagleproject/notify/triggers/aave_lpc_total_liquidity.py
eagleproject/notify/triggers/ctoken_totalborrows.py
eagleproject/notify/triggers/ctoken_totalsupply.py

Breaks the supply/borrows/liquidity notification thresholds into three separate ones.
For compound, it's 5/10/15.  For Aave, it's 2/5/10.  Can adjust them as needed later.
Closes #51

Breaks supply alert thresholds into 3 of increasing severity

---

eagleproject/core/blockchain/rpc.py
eagleproject/core/common.py
eagleproject/core/views.py
eagleproject/eagleproject/settings.py
eagleproject/notify/actions/__init__.py
eagleproject/notify/actions/objects.py
eagleproject/notify/events/__init__.py
eagleproject/notify/triggers/staking_buffer.py
eagleproject/notify/triggers/staking_paused.py
eagleproject/notify/triggers/staking_rates.py
eagleproject/notify/triggers/staking_stake.py

Adds "tags" to events(an array of strings) that can be used by actions.  Tags are set when the event is created in the triggers.  Right now, this amounts to "ogn" being the only useful tag that the `DiscordWebhook` action will detect and try and use a webhook override, if it's availalbe.  Should be pretty easy to add others if we decide to go that route.
Already configured envkey to set the override for `#ogn-monitoring`.
This also takes care of a minor bug so I may just merge and deploy this in a little bit.
Closes #36

Event tags and OGN partitioning

---

eagleproject/core/blockchain/harvest/transactions.py
eagleproject/core/views.py

Fixes staking duration math (used in `/api/v1/staking_stats_by_duration`) to include numbers in mature stakes that have not yet been withdrawn.  Basically changes staking math to only sum stakes and withdraws per user and ignore maturity dates.  Numbers check out this time between the two API endpoints.
Wasn't able to do it in a single query so it got a little out of hand...
Closes #81

Staking math correction

---

eagleproject/core/common.py
eagleproject/notify/actions/objects.py
eagleproject/notify/triggers/compound_governoralpha_proposals.py

Discord webhooks embeds only allow 2048 characters in their `descrpition` field.  This adds truncation to the compound prop trigger, and general truncation to the action if it comes to that.
Closes #92

Discord webhook description limits

---

eagleproject/core/views.py

Remove extra data collection from the dashboard view.  This should eliminate (reduce?) conflicts with other data harvesting.
CC @DanielVF

Reduce harvest on dashboard page loads

---

eagleproject/core/blockchain/harvest/transactions.py

When unable to decode amount from the transaction, fallback to the event.
Closes #85

Fallback to event amount data if decoding is impossible

---

eagleproject/notify/triggers/aave_lpc_total_liquidity.py
eagleproject/notify/triggers/ctoken_totalborrows.py
eagleproject/notify/triggers/ctoken_totalsupply.py

Removes some editorialization I put into some notifications that makes no sense in hindsight.  And bumps the cUSDT notification thresholds for totalSupply and totalBorrows because it's such a smaller pool on the whole.

Adjust notification language and thresholds

---

eagleproject/core/templates/address.html

Much more logical.
Before:
After:

Flip the current balance to be on top.

---

eagleproject/core/blockchain/apy.py

We temp changed to 29 days to avoid a data bug due to the resolution upgrade. This undoes that that, since we no longer need it.

Switch back to 30 days for APY calculations

---

eagleproject/notify/triggers/staking_buffer.py

Adjusts staking notification thresholds since we're letting it drain further.

Change staking notification thresholds to 250k, 100k, and 50k

---

eagleproject/core/templates/dashboard.html

this adds a chart to dashboard showing OUSD supply relative to total stablecoin supply on Ethereum, issue #216
https://dune.com/queries/1149021/1961517

add OUSD relative supply chart

---

eagleproject/core/templates/dashboard.html
eagleproject/core/views.py

This tackles https://github.com/OriginProtocol/ousd-analytics/issues/195
I am fetching token holders value from latest weekly report as it's a pretty intensive computation.
I verified locally the token holders number corresponds to the latest weekly report number (see screenshots). This number is not the correct one since I don't have all the reports computed locally.

Add total number of token holders

---

eagleproject/core/static/core/strategist/abi_vault_value_checker.js
eagleproject/core/static/core/strategist/strategist_validator.js

This blindly replaces the contract address and ABI for the new [VaultValueChecker](https://etherscan.io/address/0xEEcD72c99749A1FC977704AB900a05e8300F4318#code), which I'm unable to test in my local environment.

Update strategist validator with new contract

---

eagleproject/core/blockchain/harvest/transaction_history.py

Fixes a bug where "Week" is used instead of "Month" in emails

Fix texts on emails

---

eagleproject/core/blockchain/harvest/snapshots.py
eagleproject/core/blockchain/harvest/transaction_history.py
eagleproject/core/views.py

The relevant accounting/data exposed for step 0.75 in Proof of Yield.
We want to be able fill out this section.
In this PR, I made a change to how the `change` (in percent) from one day to another was calculated. Previously, `change` was calculated by finding the difference in between `rebasing_credits_per_token` at the beginning and end of the time period, and dividing by the `rebasing_credits_per_token` at the beginning of the time period to receive a percentage. 
`change = 1 - (s.rebasing_credits_per_token / last_snapshot.rebasing_credits_per_token)`
However, later using this value to compute the total yield resulted in a discrepancy between the total yield, and the sum of the yields from the rebase events.
`s.gain = change * (s.computed_supply - s.non_rebasing_supply)`
This isn't …

PoY-v0.75 accounting

---

eagleproject/core/templates/analytics_report_v2_base.html
eagleproject/core/templatetags/blockchain.py

This is a blind PR but here are the intended outcomes:

Update precision for OETH metrics

---

eagleproject/core/blockchain/harvest/blocks.py
eagleproject/core/views.py
eagleproject/eagleproject/urls.py

- Adds a TVL history endpoint
- Adds circulating supply, protocol-owned supply, block time and block numbers to `/strategies` endpoint
To get 7-day TVL history:
```
GET /api/v2/ousd/tvl_history/7
```
[Here's a sample 7-day response](https://github.com/OriginProtocol/ousd-analytics/files/12430847/7day-response.txt)

Add TVL history endpoint

---

eagleproject/notify/events/__init__.py
eagleproject/notify/main.py
eagleproject/notify/triggers/vault_oracle.py
eagleproject/notify/views.py
eagleproject/scripts/gc.py

**DO NOT MERGE YET**
Haven't tested this yet to be merge-ready. This is probably less-performant than the existing code (since the existing code did one big query whereas this does a `get_or_create` in a loop). However, we don't have that many events firing at once, so it should be fine

Event-specific dedupe window
