eagleproject/core/sigs.py, eagleproject/notify/triggers/governable_transfer.py, eagleproject/notify/triggers/proxy_upgraded.py
Adds `Governable` and `BaseUpgradeabilityProxy` event notification triggers.
Closes #18
=> Governable and proxy triggers

eagleproject/core/sigs.py, eagleproject/notify/triggers/timelock_admin.py, eagleproject/notify/triggers/timelock_delay.py
Pretty straight forward addition of a few triggers for `NewAdmin`, `NewPendingAdmin`, and `NewDelay`.
Closes #15
=> Adds triggers for admin and delay events

eagleproject/core/templates/apr_index.html, eagleproject/core/templates/dashboard.html, eagleproject/core/views.py
=> 2-day average

eagleproject/core/views.py, eagleproject/eagleproject/urls.py
Requirement for https://github.com/OriginProtocol/origin-website/issues/571
=> add API to get staking stats by duration

eagleproject/core/templates/powermint.html, eagleproject/core/views.py, eagleproject/eagleproject/urls.py
Draft of chart showing the costs to mint and redeem, plus the payback time at current APY rates.
=> Powermint chart draft

eagleproject/core/views.py
Fixes date math for staking stats query.  @ZaHuPro please verify this meets your criteria.
=> Fix OgnStaking query for staking stats API

eagleproject/core/blockchain/harvest.py, eagleproject/core/blockchain/rpc.py, eagleproject/core/logging.py, eagleproject/core/templatetags/blockchain.py, eagleproject/eagleproject/settings.py, eagleproject/notify/actions/objects.py, eagleproject/notify/triggers/__init__.py, eagleproject/notify/triggers/aave_proto_governance.py, eagleproject/notify/triggers/staking_stake.py, eagleproject/notify/views.py
=> Logging improvements

eagleproject/core/views.py, eagleproject/eagleproject/urls.py
=> Adds API endpoint /api/v1/pools

eagleproject/notify/triggers/ousd_totalsupply.py
Shows change in actual OUSD in the `TotalSupplyUpdated` event notification.
Closes #37
=> Show change in totalSupply in TotalSupplyUpdated notification

eagleproject/core/blockchain/decode.py
=> decode_call is for humans, so use hex and not byte strings

eagleproject/notify/triggers/aave_lpc_total_liquidity.py, eagleproject/notify/triggers/ctoken_totalborrows.py
=> Fixes thresholds in notifications

eagleproject/core/coingecko.py, eagleproject/core/views.py
=> /pools API endpoint should be in USD

eagleproject/core/blockchain/harvest/snapshots.py
Adds 3pool asset block snapshots back in.
=> Add 3pool asset block snapshots

eagleproject/core/blockchain/const.py, eagleproject/core/blockchain/sigs.py, eagleproject/core/common.py, eagleproject/notify/events/__init__.py, eagleproject/notify/triggers/__init__.py, eagleproject/notify/triggers/aave_lpc_total_liquidity.py, eagleproject/notify/triggers/assetblock_holdings.py, eagleproject/notify/triggers/vault_trustee.py
Adds a trigger when holdings change beyond thresholds. This may end up causing a bunch of false positives, so may need to be adjusted going forward.
Ref: #65, #86
=> AssetBlock change trigger

eagleproject/notify/triggers/curve_aragon_vote.py
=> Add curve DAO vote links to notification

eagleproject/notify/triggers/aave_lpc_supply_rates.py, eagleproject/notify/triggers/ctoken_supplyrates.py
=> Disables low supply rate notifications

eagleproject/notify/triggers/strategy_rewards.py
=> Resolve CRV token for rewards token collection trigger notifications

eagleproject/core/templates/powermint.html, eagleproject/core/templatetags/blockchain.py, eagleproject/core/views.py
- Update powermint with current gas prices
- Fix bug in gas prices (was using APY as gas price 🙀 )
- Change APY lines to monthly
- Zoom out chart verticaly
=> Update powermint with current gas prices.

eagleproject/core/blockchain/harvest/snapshots.py, eagleproject/core/blockchain/rpc.py, eagleproject/core/blockchain/sigs.py, eagleproject/notify/triggers/vault_oracle.py
=> ABI changes for priceUSDMint and priceUSDRedeem

eagleproject/core/blockchain/harvest/snapshots.py, eagleproject/core/views.py
Fixes the incorrect negative daily apr's that show up some times.
=> Include future fee when doing potential rebase calculations

eagleproject/core/blockchain/harvest/snapshots.py
Adds tracking DAI in the Compound strategy.
Closes #136
=> DAI in compound strategy

README.md, eagleproject/core/blockchain/const.py, eagleproject/core/blockchain/harvest/transaction_history.py, eagleproject/core/models.py, eagleproject/core/templates/analytics_report.html, eagleproject/core/templates/analytics_report_email.html, eagleproject/core/templates/analytics_reports.html, eagleproject/core/templatetags/blockchain.py, eagleproject/core/views.py, eagleproject/eagleproject/urls.py
- Add new analytics data points 
- show only limited data in reports page
- show detailed data on report detail page
=> Sparrow dom/analytics polish

eagleproject/core/blockchain/harvest/transaction_history.py, eagleproject/core/blockchain/harvest/transactions.py, eagleproject/core/views.py, eagleproject/eagleproject/urls.py
- fix problem of unknown transactions
- add log_index to transaction api object
- disable parallelism when fetching transactions
=> Sparrow dom/tx history v2

eagleproject/notify/triggers/__init__.py
Skipping Aave v1 notification triggers to reduce noise.  v2 snapshots should be added to replace v1 data.
There's some formatting stuff too.  Started running black with this project.
=> Aave v1 notification suppression

eagleproject/core/templates/dashboard.html
add Dune analytics to the landing page
=> add Dune analytics to the landing page

eagleproject/core/blockchain/addresses.py
=> Add convex strategy name resolution

eagleproject/notify/triggers/staking_buffer.py
=> Lower the staking buffer

eagleproject/core/blockchain/harvest/transaction_history.py
=> fix log ordering

eagleproject/core/templates/dashboard.html
adding OUSD protocol revenue chart to dashboard
=> add protocol revenue chart

eagleproject/core/common.py
Past me created dumb code making things way more complex than they needed to be while introducing a bug in number formatting.  This simplifies things greatly by just using python's own string formatting.
=> Cleanup number formatting

eagleproject/eagleproject/.env.dev, eagleproject/eagleproject/settings.py, eagleproject/requirements.txt
Adds sentry for reporting production errors. SENTRY_DSN variable should be set when deploying.
References issue: #214
=> Add sentry

eagleproject/core/views.py, eagleproject/eagleproject/urls.py
add api routes for strategy and collateral breakdown
=> add api routes

eagleproject/notify/triggers/vault_strategies.py
=> Fix data decoding in vault_strategies

eagleproject/core/views.py, eagleproject/eagleproject/urls.py
add trailing apy history api route for past 90 days
=> add trailing apy history route

eagleproject/core/views.py, eagleproject/eagleproject/urls.py
add api route for trailing apy history of last 90 days, add metastrategy stats to endpoints
=> add trailing apy history + update /strategies and /collateral

eagleproject/core/blockchain/strategies.py
rename OUSD MetaStrategy to Convex OUSD+3Crv and Convex Strategy to Convex DAI+USDC+USDT for consistency and to simplify frontend
related PR: https://github.com/OriginProtocol/ousd.com/pull/45
=> rename convex strategies

eagleproject/core/templates/base.html, eagleproject/core/templates/public_dashboards.html, eagleproject/core/views.py, eagleproject/eagleproject/urls.py
- Adds grafana public dashboards to analytics
- Also adds some navigation links
=> add grafana dashboards

eagleproject/core/templates/base.html, eagleproject/core/templates/public_dashboards.html, eagleproject/core/views.py
=> better mobile treatment

eagleproject/core/templates/public_dashboards.html
remove time ranges on embedded panels
=> remove time ranges on embedded panels

eagleproject/core/templates/analytics_report.html, eagleproject/core/templates/base.html
change analytics reports to new design, similar to emails
requires regenerating data for reports to pick up new rows and fix broken endpoints
=> new report design

eagleproject/core/templates/analytics_report.html, eagleproject/core/templates/analytics_report_email.html, eagleproject/core/views.py, eagleproject/eagleproject/urls.py
- add temporary option to remove reports, as generating the latest report before end of week prevents analytics email being sent
- weekly/monthly labelling fix
- fix basis point precision
=> fix email sending

eagleproject/core/static/core/strategist/abi_vault.js, eagleproject/core/static/core/strategist/strategist_validator.js
With the new style allocations, we also need to update the strategist action validator.
=> Update validator to support new direct reallocations

eagleproject/core/templates/public_dashboards.html
=> correct dashboard panel ids

eagleproject/core/blockchain/harvest/transaction_history.py, eagleproject/core/blockchain/rpc.py, eagleproject/scripts/backfill_monthly.py, eagleproject/scripts/backfill_weekly.py
- change report generation to recalculate supply data
- fix historical daily fee calculation
- fix pending rebase calculation
- add backfill script for weekly and monthly reports
=> report and collateral calculation fixes

eagleproject/core/blockchain/harvest/transaction_history.py, eagleproject/scripts/send_monthly_email.py, eagleproject/scripts/send_weekly_email.py
fix bug in email sending and add option to resend email
=> fix email sending and add scripts

eagleproject/core/views.py
=> remove csrf flag

eagleproject/core/blockchain/harvest/snapshots.py, eagleproject/core/blockchain/harvest/transaction_history.py, eagleproject/eagleproject/urls.py
- Compute fee based on Buyback upgrade block number
- Optimize few more queries
- Update transaction history endpoint to never return in scientific notation 
- Fix incorrect skipping of SupplySnapshot/Day model data fetch
=> OETH bug fixes

eagleproject/core/blockchain/harvest/snapshots.py, eagleproject/core/blockchain/strategies.py, eagleproject/core/models.py, eagleproject/core/views.py, eagleproject/scripts/recompute_oeth_supplysnapshot.py
- Fix supply snapshot calculations
- Add script update/recompute existing OETH snapshots
- Return 8 decimals of yield for OETH
=> Fix pending yields and lifetime earnings

eagleproject/core/blockchain/harvest/snapshots.py, eagleproject/core/views.py, eagleproject/scripts/recompute_oeth_supplysnapshot.py
- Fixes computed supply calculation
=> Use value instead of total

eagleproject/core/utils.py, eagleproject/core/views.py
I added a decoder for Decimal values, but I don't know if we need to add in more places after
=> fix: add decimal decoding for json

eagleproject/notify/triggers/failed_transactions.py
This will ensure we get tagged on all failed tx messages
=> Change failed tx severity to high

eagleproject/core/templates/analytics_report_v2_base.html, eagleproject/core/templatetags/blockchain.py
- Change wrong 7d APY label to 30d
- Fix double negative sign
=> Typography fixes

eagleproject/core/static/core/strategist/abi_buyback.js, eagleproject/core/static/core/strategist/strategist_validator.js, eagleproject/core/templates/strategist.html
=> decode buyback data

eagleproject/core/blockchain/harvest/snapshots.py, eagleproject/notify/triggers/vault_oracle.py
Related to https://github.com/OriginProtocol/origin-dollar/issues/1368
Governance proposal: <https://governance.ousd.com/proposals/92067299921253167171731269251828366645465100428916088471428281989790584946916>
=> Fix oracle triggers

eagleproject/core/blockchain/dripper.py, eagleproject/core/blockchain/rpc.py, eagleproject/core/views.py, eagleproject/eagleproject/urls.py
Sample API responses:
For OUSD:
```
{
"token": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
"drip_rate": "0.000042694846852197",
"rate_per_minute": "0.002561690811131820",
"rate_per_hour": "0.153701448667909200",
"rate_per_day": "3.688834768029820800",
"token_balance": "12.224750452764986537",
"collectable": "1.164032304578299008",
"updated_at": "2023-08-29T14:34:20.422"
}
```
For OETH:
```
{
"token": "0xdac17f958d2ee523a2206206994597c13d831ec7",
"drip_rate": "0.000487",
"rate_per_minute": "0.029220",
"rate_per_hour": "1.753200",
"rate_per_day": "42.076800",
"token_balance": "295.104198",
"collectable": "13.277568",
"updated_at": "2023-08-29T14:34:25.824"
}
```
=> Add Dripper endpoints
